apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: the-place-ingress
spec:
  rules:
  - http:
      paths:
      - path: /grafana
        pathType: Prefix
        backend:
          service:
            # TODO: make this smarter
            name: {{ .Values.ingress.grafana.service.name }}
            port:
              number: 80